Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.define "scala" do |node|
    node.vm.box = "antapos/ubuntu-trusty64-jdk8-maven"
    node.vm.box_version = "0.1"
    node.vm.hostname = "scala"
    node.vm.provision "shell", path: "provision/sbt.sh"
  end

end