Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "4"
  end

  config.vm.define "scala" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "scala"
    node.vm.provision "shell", path: "provision/sbt.sh"
  end

end