Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", host: 8080, guest: 80

  config.vm.network "private_network", type: "dhcp"

  config.vm.network "public_network", bridge: "en0: Ethernet"
  config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"

  config.vm.provision "shell", path: "nginx.sh", privileged: false

end
