Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-16.04"
    node1.vm.network "public_network", ip: "10.15.4.201"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/ubuntu-16.04"
    node2.vm.network "public_network", ip: "10.15.4.202"
  end

end