Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.define "node_1" do |node_1|
    node_1.vm.box = "ubuntu/trusty64"
    node_1.vm.network "public_network", ip: "10.15.4.xx1"
  end

  config.vm.define "node_2" do |node_2|
    node_2.vm.box = "ubuntu/trusty64"
    node_2.vm.network "public_network", ip: "10.15.4.xx2"
  end

  config.vm.define "node_3" do |node_3|
    node_3.vm.box = "ubuntu/trusty64"
    node_3.vm.network "public_network", ip: "10.15.4.xx3"
  end

  config.vm.define "node_4" do |node_4|
    node_4.vm.box = "ubuntu/trusty64"
    node_4.vm.network "public_network", ip: "10.15.4.xx4"
  end

end
