Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", path: "nginx.sh", privileged: false

end
