Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", host: 8080, guest: 80

  config.vm.provision "shell", path: "deployLAMP.sh", privileged: false

  config.vm.synced_folder "www", "/var/www"

end
