Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "web_forward" do |web|
    web.vm.provision "shell", path: "nginx.sh", privileged: false
    config.vm.network "forwarded_port", host: 8080, guest: 80
  end

  config.vm.define "web_public" do |web|
    web.vm.provision "shell", path: "nginx.sh", privileged: false
    config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
  end

end
