Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "public_network", ip: "10.0.0.200"

  config.vm.provision "shell", path: "nginx.sh", privileged: false

end
